# This is a basic workflow to help you get started with Actions

name: root-conda-nightly

# Controls when the workflow will run
on: workflow_dispatch

env:
  PYTHONUNBUFFERED: true
  OS_APPLICATION_CREDENTIAL_ID: '7f5b64a265244623a3a933308569bdba'
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
  OS_AUTH_TYPE: 'v3applicationcredential'
  OS_AUTH_URL: 'https://keystone.cern.ch/v3'
  OS_IDENTITY_API_VERSION: 3
  OS_INTERFACE: 'public'
  OS_REGION_NAME: 'cern'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on:
      - self-hosted
      - linux
      - x64

    container:
      image: registry.cern.ch/root-ci/alma9:buildready
      options: '--security-opt label=disable --rm' # ALSO UPDATE BELOW!
      env:
        PYTHONUNBUFFERED: true
        OS_APPLICATION_CREDENTIAL_ID: '7f5b64a265244623a3a933308569bdba'
        OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
        OS_AUTH_TYPE: 'v3applicationcredential'
        OS_AUTH_URL: 'https://keystone.cern.ch/v3'
        OS_IDENTITY_API_VERSION: 3
        OS_INTERFACE: 'public'
        OS_REGION_NAME: 'cern'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Build ROOT and run unittests
        run: ./build_master.sh --clean; ./build_master.sh --build-number="$(date +%Y%M%d)" --test

      - name: Generate compressed artifact
        run: |
          mv root-feedstock/build_artifacts root_conda_nightly_$(date +%Y%m%d)
          tar -czvf latest_conda_nightly.tgz root_conda_nightly_$(date +%Y%m%d)

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ROOT conda nightly
          path: latest_conda_nightly.tgz
          if-no-files-found: error
